print(bool(True))      
print(bool(False))
print(bool(0))    
print(bool(1))  
print(bool("Python"))  
print(bool("")) 
print(bool(" "))   
print(bool("0"))  
print(bool([1, 2]))   
print(bool([]))       
print(bool((1, 2)))    
print(bool(()))     